# raise lançando erros

print(1,2,3)
raise ValueError('Valor inválido')
print(4,6,5)